"use client";
import { useEffect, useState } from "react";
import { RequireAuth } from "@/components/auth/require-auth";
import { PageContainer, StatePanel } from "@/components/ui/primitives";
import { LifeCard } from "@/components/design/memory";
import { IC } from "@/components/design/icons";
import type { LifeContext } from "@/types/reibry";
import { invalidateQueryCache, readQueryCache, writeQueryCache } from "@/lib/client/query-cache";
import Link from "next/link";
import { partitionLifeContexts } from "@/lib/life/management";
type SaveState = "idle" | "saving" | "saved";
export default function Life() { const [text, setText] = useState(""); const [items, setItems] = useState<LifeContext[]>(() => readQueryCache<LifeContext[]>("life") || []); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [state, setState] = useState<SaveState>("idle");
  async function load() { const response = await fetch("/api/life", { cache: "no-store" }); const body = await response.json(); if (!response.ok || !Array.isArray(body.data)) throw new Error(body.error?.message || "Unable to load life contexts."); setItems(body.data as LifeContext[]); writeQueryCache("life", body.data as LifeContext[]); invalidateQueryCache("today"); }
  useEffect(() => { let cancelled = false; fetch("/api/life", { cache: "no-store" }).then(async (response) => { const body = await response.json(); if (!response.ok || !Array.isArray(body.data)) throw new Error(body.error?.message || "Unable to load life contexts."); if (!cancelled) { setItems(body.data as LifeContext[]); writeQueryCache("life", body.data as LifeContext[]); } }).catch((cause) => { if (!cancelled) setError(cause instanceof Error ? cause.message : "Unable to load life contexts."); }); return () => { cancelled = true; }; }, []);
  async function submit() { if (!text.trim() || state === "saving") return; setState("saving"); setError(""); setMessage(""); try { const response = await fetch("/api/life/create", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text: text.trim(), timezone: Intl.DateTimeFormat().resolvedOptions().timeZone }) }); const body = await response.json(); if (!response.ok || !Array.isArray(body.data?.contexts)) throw new Error(body.error?.message || "Unable to save life context."); const contexts = body.data.contexts as LifeContext[]; const limited = body.data?.metadata?.status === "partial"; setText(""); let matched = 0; let matchingFailed = false; for (const context of contexts) { try { const matchResponse = await fetch("/api/context/match", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ lifeContextId: context.id }) }); const matchBody = await matchResponse.json(); if (!matchResponse.ok || !Array.isArray(matchBody.data?.matches)) { matchingFailed = true; continue; } matched += matchBody.data.matches.length; } catch { matchingFailed = true; } } setMessage(limited ? "Added to Life. REIBRY had limited information available." : matchingFailed ? "Life event saved. REIBRY could not check related Memories right now." : matched > 0 ? "Life event saved. Related Memories found." : "Life event saved. No relevant Memories found yet."); setState("saved"); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save life context."); setState("idle"); } }
  return <RequireAuth><PageContainer><p className="section-label">Life chronology</p><h1 className="page-h1">What&apos;s happening<br />in your world?</h1><p className="page-sub">Tell REIBRY what&apos;s coming up, changing, or important.</p>
    <div className="gap-section" /><form onSubmit={(event) => { event.preventDefault(); void submit(); }} className="life-composer">
      <label htmlFor="life-input" className="sr-only">Life context</label><textarea id="life-input" disabled={state === "saving"} value={text} onChange={(event) => setText(event.target.value)} placeholder="An exam next week, a trip you're planning, a new project…" className="life-textarea" />
      <div className="life-composer-parse"><p className="life-parse-note">Tell it in your own words</p></div>
      <div className="life-composer-footer"><button type="submit" disabled={!text.trim() || state === "saving"} className="btn-primary">{state === "saving" ? "Saving…" : "Add to Life"}<span aria-hidden="true">{IC.plus}</span></button></div>
    </form>
    {message && <StatePanel>{message}</StatePanel>}{error && <StatePanel tone="error">{error}</StatePanel>}
    <div className="gap-section" />{(() => { const grouped = partitionLifeContexts(items); return <><div className="life-list-header"><h2 className="section-heading">Coming up</h2><span className="life-count">{grouped.upcoming.length}</span></div>{!grouped.upcoming.length && !error && <StatePanel>Nothing dated is coming up yet.</StatePanel>}<div className="stack">{grouped.upcoming.slice(0, 4).map((context) => <LifeCard key={context.id} context={context} />)}</div>{grouped.undated.length > 0 && <><div className="life-list-header"><h2 className="section-heading">Needs a date</h2><span className="life-count">{grouped.undated.length}</span></div><div className="stack">{grouped.undated.slice(0, 2).map((context) => <LifeCard key={context.id} context={context} />)}</div></>}<Link className="btn-ghost life-manage-link" href="/life/manage">Manage Life <span aria-hidden="true">{IC.arrowR}</span></Link></>; })()}
  </PageContainer></RequireAuth>;
}
